name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Yarn Cache
        uses: actions/cache@v2
        with:
          path: |
            ./.yarn/cache
            ./.yarn/unplugged
            ./.yarn/install-state.gz
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - run: nix shell .#ci --command yarn install
      - run: nix shell .#ci --command yarn build
      - run: nix shell .#ci --command yarn typecheck
      - run: nix shell .#ci --command yarn lint:ci
      - run: nix shell .#ci --command yarn test
      - run: nix shell .#ci --command yarn dlx @yarnpkg/doctor
      - run: nix shell .#ci --command yarn size
