name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14.x
      - name: Yarn Cache
        uses: actions/cache@v2
        with:
          path: |
            ./.yarn/cache
            ./.yarn/unplugged
            ./.yarn/install-state.gz
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - run: yarn install
      - run: yarn build
      - run: yarn typecheck
      - run: yarn lint:ci
      - run: yarn test
      - run: yarn dlx @yarnpkg/doctor
      - run: yarn size
